config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :scripts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/script.rb
class Script < ApplicationRecord
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/scripts_controller.rb
class ScriptsController < ApplicationController
  before_action :set_script, only: [:show, :edit, :update, :destroy]

  # GET /scripts
  # GET /scripts.json
  def index
    @scripts = Script.all
  end

  # GET /scripts/1
  # GET /scripts/1.json
  def show
  end

  # GET /scripts/new
  def new
    @script = Script.new
  end

  # GET /scripts/1/edit
  def edit
  end

  # POST /scripts
  # POST /scripts.json
  def create
    @script = Script.new(script_params)

    respond_to do |format|
      if @script.save
        format.html { redirect_to @script, notice: 'Script was successfully created.' }
        format.json { render :show, status: :created, location: @script }
      else
        format.html { render :new }
        format.json { render json: @script.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scripts/1
  # PATCH/PUT /scripts/1.json
  def update
    respond_to do |format|
      if @script.update(script_params)
        format.html { redirect_to @script, notice: 'Script was successfully updated.' }
        format.json { render :show, status: :ok, location: @script }
      else
        format.html { render :edit }
        format.json { render json: @script.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scripts/1
  # DELETE /scripts/1.json
  def destroy
    @script.destroy
    respond_to do |format|
      format.html { redirect_to scripts_url, notice: 'Script was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_script
      @script = Script.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def script_params
      params.require(:script).permit(:title, :data)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scripts_helper.rb
module ScriptsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Strandweaver Editor
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .container-fluid
      = yield

app/views/scripts/_form.html.slim
= form_for @script do |f|
  - if @script.errors.any?
    #error_explanation
      h2 = "#{pluralize(@script.errors.count, "error")} prohibited this script from being saved:"
      ul
        - @script.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :data
    = react_component "ScriptEditor", initialData: @script.data
  .actions = f.submit

app/views/scripts/edit.html.slim
h1 Editing script

== render 'form'

=> link_to 'Show', @script
'|
=< link_to 'Back', scripts_path

app/views/scripts/index.html.slim
h1 Listing scripts

table
  thead
    tr
      th Title
      th Data
      th
      th
      th

  tbody
    - @scripts.each do |script|
      tr
        td = script.title
        td = script.data
        td = link_to 'Show', script
        td = link_to 'Edit', edit_script_path(script)
        td = link_to 'Destroy', script, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Script', new_script_path

app/views/scripts/new.html.slim
h1 New script

== render 'form'

= link_to 'Back', scripts_path

app/views/scripts/show.html.slim
p#notice = notice

p
  strong Title:
  = @script.title
p
  strong Data:
  = @script.data

=> link_to 'Edit', edit_script_path(@script)
'|
=< link_to 'Back', scripts_path